packages:
  - apps/*
  - packages/*
  - examples/*

allowBuilds:
  baileys: false
  ffmpeg-static: true
  protobufjs: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vite-plus: 0.2.2
minimumReleaseAgeExclude:
  - baileys@7.0.0-rc14
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
